! Generated by make_vegetable_driver. DO NOT EDIT
program main
    implicit none

    call run()
contains
    subroutine run()
        use rocket_test, only: &
                rocket_rocket => test_rocket
        use vegetables, only: test_item_t, test_that, run_tests

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(1)

        individual_tests(1) = rocket_rocket()
        tests = test_that(individual_tests)

        call run_tests(tests)
    end subroutine
end program
