@startuml
Title Rocket API: Classes Explicitly Referenced in the Main Program
class motor_t {
  define( input_file : character(len=*))
  chamber() : chamber_t
  dt() : real
  t_max() : real
  d_dt(persistent_state_t) : state_rate_t
}

motor_t -down- persistent_state_t  : differentiates >

class persistent_state_t {
  define(input_file : character(len=*))
  operator(+)(persistent_state_t, persistent_state_t) : persistent_state_t
}
@enduml
